sudo: required
services:
  - docker
before_install:
  - docker build -t vpradeepkumar94/docker-reactjs -f Dockerfile.dev .
script:
  - docker run vpradeepkumar94/docker-reactjs npm run test -- --coverage
